[package]
name = "aoc-2023"
version = "0.1.0"
edition = "2021"

[dependencies]
resu.workspace = true
regex.workspace = true

[[bin]]
name = "2023-01"
path = "./src/day/01.rs"

[[bin]]
name = "2023-02"
path = "./src/day/02.rs"

[[bin]]
name = "2023-03"
path = "./src/day/03.rs"
