default:
    @just -l

all: day01 day02 day03 day04 day05 day07 day08 day09 day10 day13 day15

day01:
    javac -d build src/days/day01.java 
    java -cp build day01

day02:
    javac -d build src/days/day02.java
    java -cp build day02

day03:
    javac -d build src/days/day03.java
    java -cp build day03

day04:
    javac -d build src/days/day04.java
    java -cp build day04

day05:
    javac -d build src/days/day05.java
    java -cp build day05

day06:
    kotlinc -d build src/days/day06.kt
    # java -cp build day06

day07:
    javac -d build src/days/day07.java
    java -cp build day05

day08:
    node src/days/day08.js

day09:
    cargo run -q --bin 2022-09

day10:
    cargo run -q --bin 2022-10

day13:
    cargo run -q --bin 2022-13

day15:
    # requires optimizations to run in a reasonable time
    cargo run --release -q --bin 2022-15
